import type { MemoryProfile, ScanResult } from "./types";

export const demoScanResult: ScanResult = {
  root: "/demo/.codex/memories",
  sources: [
    {
      id: "demo-memory",
      path: "/demo/.codex/memories/MEMORY.md",
      relativePath: "MEMORY.md",
      kind: "registry",
      modifiedMs: 1,
      bytes: 420,
      lines: 8,
      sha256: "demo-memory-sha",
    },
    {
      id: "demo-activity",
      path: "/demo/.codex/memories/extensions/chronicle/resources/activity.md",
      relativePath: "extensions/chronicle/resources/activity.md",
      kind: "chronicle",
      modifiedMs: 1,
      bytes: 360,
      lines: 6,
      sha256: "demo-activity-sha",
    },
    {
      id: "demo-correction",
      path: "/demo/.codex/memories/extensions/ad_hoc/notes/profile.md",
      relativePath: "extensions/ad_hoc/notes/profile.md",
      kind: "adHocNote",
      modifiedMs: 1,
      bytes: 260,
      lines: 4,
      sha256: "demo-correction-sha",
    },
  ],
  entries: [
    {
      id: "demo-profile",
      topic: "profile",
      relatedTopics: [],
      title: "Current profile",
      summary: "The current durable profile says the user's primary stack is Python/Rust.",
      searchText: "The current durable profile says the user's primary stack is Python/Rust.",
      sourcePath: "MEMORY.md",
      startLine: 1,
      endLine: 8,
    },
    {
      id: "demo-activity",
      topic: "activityLog",
      relatedTopics: [],
      title: "Recent activity",
      summary: "The user inspected BeeBotOS during a recent screen recording.",
      searchText: "The user inspected BeeBotOS during a recent screen recording.",
      sourcePath: "extensions/chronicle/resources/activity.md",
      startLine: 1,
      endLine: 6,
    },
    {
      id: "demo-profile-correction",
      topic: "overrides",
      relatedTopics: ["profile"],
      title: "Profile correction",
      summary: "Memory update request: Treat Python/Rust as the current primary stack.",
      searchText: "Memory update request: Treat Python/Rust as the current primary stack.",
      sourcePath: "extensions/ad_hoc/notes/profile.md",
      startLine: 1,
      endLine: 4,
      change: {
        id: "demo-profile-change",
        operation: "replace",
        targetEntryIds: ["demo-profile"],
        revertsChangeId: null,
        createdAt: "2026-07-17T00:00:00.000Z",
      },
    },
  ],
  risks: [
    {
      id: "demo-risk",
      kind: "staleConflict",
      title: "Older stack reference",
      detail: "Older Java/Spring Boot text conflicts with the newer Python/Rust correction.",
      entryId: "demo-profile",
    },
  ],
};

export const demoMemoryProfile: MemoryProfile = {
  schemaVersion: "1",
  generatedAt: "2026-06-09T00:00:00Z",
  sourceHash: "demo-profile-source-hash",
  generator: "codex-profile-v4",
  cachePath: "/demo/.codex/memories/.backplane/profile.zh-CN.json",
  sections: [
    {
      id: "python-rust-is-current-stack",
      title: "你把 Python/Rust 作为当前主栈",
      body: "当前修正记忆显示，你希望 Backplane 优先相信 Python/Rust 是现在的主技术栈。",
      confidence: "high",
      stability: "stable",
      evidence: [
        {
          entryId: "demo-profile-correction",
          sourcePath: "extensions/ad_hoc/notes/profile.md",
          startLine: 1,
          endLine: 4,
          summary: "Treat Python/Rust as the current primary stack.",
        },
      ],
    },
    {
      id: "correction-notes-override-old-stack",
      title: "你用修正笔记覆盖旧技术栈记忆",
      body: "这段画像来自修正笔记，而不是旧摘要；旧的 Java/Spring Boot 暗示应被当作历史上下文。",
      confidence: "high",
      stability: "stable",
      evidence: [
        {
          entryId: "demo-profile-correction",
          sourcePath: "extensions/ad_hoc/notes/profile.md",
          startLine: 1,
          endLine: 4,
          summary: "Treat Python/Rust as the current primary stack.",
        },
        {
          entryId: "demo-profile",
          sourcePath: "MEMORY.md",
          startLine: 1,
          endLine: 8,
          summary: "Older profile text still appears in the memory registry.",
        },
      ],
    },
  ],
  metadata: {
    memoryRoot: "/demo/.codex/memories",
    inputEntries: 3,
    currentEntries: 1,
  },
};
