export const channels = {
  getAppUpdateState: "app:get-update-state",
  checkAppUpdate: "app:check-update",
  downloadAppUpdate: "app:download-update",
  installAppUpdate: "app:install-update",
  scanMemories: "memory:scan",
  generateMemoryProfile: "memory:generate-profile",
  startMemoryProfileGeneration: "memory:start-profile-generation",
  getMemoryProfileGeneration: "memory:get-profile-generation",
  cancelMemoryProfileGeneration: "memory:cancel-profile-generation",
  loadMemoryProfile: "memory:load-profile",
  loadAgentMemorySnapshot: "memory:load-agent-snapshot",
  getSourceExcerpt: "memory:get-source-excerpt",
  draftCorrection: "memory:draft-correction",
  draftCorrectionFromContent: "memory:draft-correction-from-content",
  writeCorrection: "memory:write-correction",
  startCodexAudit: "audit:start",
  getCodexAudit: "audit:get",
  cancelCodexAudit: "audit:cancel",
  runCodexAudit: "audit:run",
  loadSkillInventory: "skills:load",
  loadAgentConfigInventory: "agent-config:load",
  saveAgentProviderProfile: "agent-config:save",
  deleteAgentProviderProfile: "agent-config:delete",
  activateAgentProviderProfile: "agent-config:activate",
  loadMcpInventory: "mcp:load",
  revealSource: "shell:reveal-source",
} as const;
